### ISSUE TITLE
No fruit seeds from trees option in crafting table 

### ISSUE THREAD

**Issue by WebDeveloperAndrew** [notfood/RimWorld-SeedsPlease#2]
I've noticed quite a few others talking about this bug on steam, seems no fruit tree seeds are showing up to craft even with the research. I'm going to take a look and see if I can figure out why myself but I wasn't sure if you would want to take a crack at it. 
Edit: Took a look and none of the fruit trees/seeds are in the vg addon at all, that is why they aren't showing up.

**Comment by notfood** [comment]
Should be fixed in B18
