### ISSUE TITLE
Defs

### ISSUE THREAD

**Issue by TermyCornall** [notfood/RimWorld-SeedsPlease#22]
Autogenerated seeds for Alpha Biomes
Presumably you wouldn't want seed extraction jobs for the fungi, but whatevs.

SeedsPlease :: Some Seeds were autogenerated. Don't rely on autogenerated seeds, share the generated xml for proper support.

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_GiantSeptimum</defName>
  <label>ab_giantseptimum seeds</label>
  <plant>AB_GiantSeptimum</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_DeadBower</defName>
  <label>ab_deadbower seeds</label>
  <plant>AB_DeadBowerTree</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_Jungle</defName>
  <label>ab_jungle seeds</label>
  <plant>AB_JungleTree</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_SessileMechanoid</defName>
  <label>ab_sessilemechanoid seeds</label>
  <plant>AB_SessileMechanoid</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_Glowstool</defName>
  <label>ab_glowstool seeds</label>
  <plant>AB_Glowstool</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_Glowstool</defName>
  <label>extract ab_glowstool seeds</label>
  <description>Extract seeds from Fungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>RawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>RawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_Glowstool>3</Seed_AB_Glowstool>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_LilacBeacon</defName>
  <label>ab_lilacbeacon seeds</label>
  <plant>AB_LilacBeacon</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_LilacBeacon</defName>
  <label>extract ab_lilacbeacon seeds</label>
  <description>Extract seeds from AB_PurpleFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_PurpleRawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_PurpleRawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_LilacBeacon>3</Seed_AB_LilacBeacon>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_WitchesOyster</defName>
  <label>ab_witchesoyster seeds</label>
  <plant>AB_WitchesOyster</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_WitchesOyster</defName>
  <label>extract ab_witchesoyster seeds</label>
  <description>Extract seeds from AB_PinkFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_PinkRawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_PinkRawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_WitchesOyster>3</Seed_AB_WitchesOyster>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_AgaricusDomeCap</defName>
  <label>ab_agaricusdomecap seeds</label>
  <plant>AB_AgaricusDomeCap</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_AgaricusDomeCap</defName>
  <label>extract ab_agaricusdomecap seeds</label>
  <description>Extract seeds from AB_PsychotropicFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_PsychotropicFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_PsychotropicFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_AgaricusDomeCap>3</Seed_AB_AgaricusDomeCap>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_Agarilux</defName>
  <label>ab_agarilux seeds</label>
  <plant>AB_Agarilux</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_Agarilux</defName>
  <label>extract ab_agarilux seeds</label>
  <description>Extract seeds from AB_PurpleFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_PurpleRawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_PurpleRawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_Agarilux>3</Seed_AB_Agarilux>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_GiantAgarilux</defName>
  <label>ab_giantagarilux seeds</label>
  <plant>AB_GiantAgarilux</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_ArbuscularMycorrhiza</defName>
  <label>ab_arbuscularmycorrhiza seeds</label>
  <plant>AB_ArbuscularMycorrhiza</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_DribblingCap</defName>
  <label>ab_dribblingcap seeds</label>
  <plant>AB_DribblingCap</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_DribblingCap</defName>
  <label>extract ab_dribblingcap seeds</label>
  <description>Extract seeds from AB_WeaponPoisonDart</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_WeaponPoisonDart</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_WeaponPoisonDart</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_DribblingCap>3</Seed_AB_DribblingCap>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_RecurvedStropharia</defName>
  <label>ab_recurvedstropharia seeds</label>
  <plant>AB_RecurvedStropharia</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_SlimyPholiota</defName>
  <label>ab_slimypholiota seeds</label>
  <plant>AB_SlimyPholiota</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_SlimyPholiota</defName>
  <label>extract ab_slimypholiota seeds</label>
  <description>Extract seeds from AB_BlueFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_BlueRawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_BlueRawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_SlimyPholiota>3</Seed_AB_SlimyPholiota>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_GlowingAgarilux</defName>
  <label>ab_glowingagarilux seeds</label>
  <plant>AB_GlowingAgarilux</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_GlowingAgarilux</defName>
  <label>extract ab_glowingagarilux seeds</label>
  <description>Extract seeds from AB_PurpleFungus</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_PurpleRawFungus</li>
        </thingDefs>
      </filter>
      <count>4</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_PurpleRawFungus</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_GlowingAgarilux>3</Seed_AB_GlowingAgarilux>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_Slimy</defName>
  <label>ab_slimy seeds</label>
  <plant>AB_SlimyTree</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_Slimy</defName>
  <label>extract ab_slimy seeds</label>
  <description>Extract seeds from AB_Slime</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_RawSlime</li>
        </thingDefs>
      </filter>
      <count>7</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_RawSlime</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_Slimy>3</Seed_AB_Slimy>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_LargeSlimy</defName>
  <label>ab_largeslimy seeds</label>
  <plant>AB_LargeSlimyTree</plant>
</SeedsPlease.SeedDef>

<RecipeDef ParentName="ExtractSeed">
  <defName>ExtractSeed_AB_LargeSlimy</defName>
  <label>extract ab_largeslimy seeds</label>
  <description>Extract seeds from AB_Slime</description>
  <ingredients>
    <li>
      <filter>
        <thingDefs>
          <li>AB_RawSlime</li>
        </thingDefs>
      </filter>
      <count>7</count>
    </li>
  </ingredients>
  <fixedIngredientFilter>
    <thingDefs>
      <li>AB_RawSlime</li>
    </thingDefs>
  </fixedIngredientFilter>
  <products>
    <Seed_AB_LargeSlimy>3</Seed_AB_LargeSlimy>
  </products>
</RecipeDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_FanPalm</defName>
  <label>ab_fanpalm seeds</label>
  <plant>AB_FanPalm</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_AB_KeeningCordax</defName>
  <label>ab_keeningcordax seeds</label>
  <plant>AB_KeeningCordax</plant>

**Comment by notfood** [comment]
Same issue here, xml eaten by github. Include as file

**Comment by TermyCornall** [comment]
I included it in the other issue, so I suppose we can close this one.
