### ISSUE TITLE
Defs for Nature's Pretty Sweet

### ISSUE THREAD

**Issue by TermyCornall** [notfood/RimWorld-SeedsPlease#23]
Autogenerated defs for TKKN's Nature's Pretty Sweet.
Note that some trees - particularly the "dead redwood" - probably shouldn't have seeds.
Also, the auto-generated prices for these seeds... well, I got one redwood seed at the start of a colony, and was instantly deathballed on the next raid.

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_Ocotillo</defName>
  <label>ocotillo seeds</label>
  <plant>TKKN_TreeOcotillo</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_Baobab</defName>
  <label>baobab seeds</label>
  <plant>TKKN_PlantTreeBaobab</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_Gum</defName>
  <label>gum seeds</label>
  <plant>TKKN_PlantTreeGum</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_Redwood</defName>
  <label>redwood seeds</label>
  <plant>TKKN_PlantTreeRedwood</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_OldGrowth_Oak</defName>
  <label>oldgrowth_oak seeds</label>
  <plant>TKKN_OldGrowth_PlantTreeOak</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_OldGrowth_Hazelnut</defName>
  <label>oldgrowth_hazelnut seeds</label>
  <plant>TKKN_OldGrowth_PlantTreeHazelnut</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_Hazelnut</defName>
  <label>hazelnut seeds</label>
  <plant>TKKN_PlantTreeHazelnut</plant>
</SeedsPlease.SeedDef>

<SeedsPlease.SeedDef ParentName="SeedBase">
  <defName>Seed_RedwoodDead</defName>
  <label>redwooddead seeds</label>
  <plant>TKKN_PlantTreeRedwoodDead</plant>
</SeedsPlease.SeedDef>

**Comment by notfood** [comment]
Include it as file, the github markdown ate the xml

**Comment by TermyCornall** [comment]
Oops sorry! Didn't even notice. Give me a moment.

**Comment by TermyCornall** [comment]
[AB_seeds.txt](https://github.com/notfood/RimWorld-SeedsPlease/files/4309842/AB_seeds.txt)
[NatureIsSweet_seeds.txt](https://github.com/notfood/RimWorld-SeedsPlease/files/4309847/NatureIsSweet_seeds.txt)

**Comment by notfood** [comment]
I added them. I had NPS before but I didn't have the ID, it hasn't changed at all. It's not there in github yet until Tynan fixes the patch override issue.

**Comment by notfood** [comment]
Published to steam
