### ISSUE TITLE
Survival Tools compatibility

### ISSUE THREAD

**Issue by LecrisUT** [notfood/RimWorld-SeedsPlease#26]
Hey there, someone at my mod mentioned that there is an incompatibility between `SurvivalTools` and `SeedsPlease`, i.e. seeds don't drop when cutting trees. This is because in the current implementation SurvivalTools has a custom `JobDriver_PlantWork` (I'm thinking of improving it but at a much later time). [Here](https://github.com/LecrisUT/SurvivalTools/blob/master/Source/SurvivalTools/AI/JobDriver_PlantWork.cs) is the relevant file.

I do not have much time this week to write the patch. Can you add a patch on your end. If I do any changes that effect your patch next time I'll make sure to make a relevant PR as needed.

**Comment by notfood** [comment]
I too have a custom JobDriver_PlantWork. Unless we both switch to transpiling the base class, compatibility is complicated.

**Comment by LecrisUT** [comment]
I think XND has just copy-pasted the old `JobDriver_PlantWork`. I am planning to use a transpiler later on instead.

Hmm I think the best way would be to copy your `JobDriver` and add a patch to it. So I guess it should be on my side. Is there anything I should be aware of differences between tree and plants? Different sound or anything?

**Comment by notfood** [comment]
I'll switch to transpiling it. If we both use relative transpilers it shouldn't cause issues.

**Comment by LecrisUT** [comment]
Ok. I'll get back to you next week when I've done my side as well, and see how it behaves then. See you then :)

**Comment by LecrisUT** [comment]
Update: I have finished implementing my side of the patch, and it works perfectly. You do not actually need to switch to transpiling, my automating patching has made it compatible with your method as well.

Although you should check the `JobDriver_PlantWork` of recent versions. there is a quest-check you might have to add.

**Comment by notfood** [comment]
Yeah, seems planting quests aren't completing
