### ISSUE TITLE
how to add onDemand defs?

### ISSUE THREAD

**Issue by AintAbaFault** [notfood/RimWorld-SeedsPlease#3]
I'd like to add support for:
[Jecrell's Tobacco & Dry Leaves](https://ludeon.com/forums/index.php?topic=36823.0) (tobacco plant), [Cupro's Drinks](https://ludeon.com/forums/index.php?topic=32190#msg329350) (Frass Root and Coffee) and [Additional Joy Objects](https://ludeon.com/forums/index.php?topic=32190#msg329351) (Spectago).

I tried to do replicate the steps in [this commit](https://github.com/notfood/RimWorld-SeedsPlease/commit/35db1e2b0956dee12a8f5f8f036866a45e86155c), but I have no idea how to include the onDemand folder (do I have to rebuild Assemblies/LoadOnDemand.dll?).

I published my changes to this [fork](https://github.com/AintAbaFault/RimWorld-SeedsPlease). Help would be greatly appreciated.

**Comment by notfood** [comment]
I checked your changes and they all should work. No need to rebuild any dll. Just submit the PR I'll approve it.

Here is LoadOnDemand.dll source if you want to take al look:
https://gist.github.com/notfood/1e42aa1748c3fbaa66867a6cb0b430c8

The usage is to just include LoadOnDemand.dll into your Assemblies folder, then create the folder Defs_OnDemand, create a subfolder with the Defs you want included, then add the LoadOnDemand.PatchOperationLoadOnDemand to point to that folder if the mod name is detected.

**Comment by AintAbaFault** [comment]
Everything works now and I created a pull request. The issue was, that I didnt load seedsPlease before the other mods.

thanks for the fast reply and this awesome mod.
