### ISSUE TITLE
Add psd seed template

### ISSUE THREAD

**Issue by shikulja** [notfood/RimWorld-SeedsPlease#34]
to rewrite the inscription in your language.
An emptybag texture without a label would be enough
https://github.com/notfood/RimWorld-SeedsPlease/blob/master/Textures/Things/Item/Seeds/empty%20bag.png

but it would be even easier if there is a complete template with all seeds, so as not to do double work.

**Comment by notfood** [comment]
I don't have the original. This one texture came from HardcoreSK.
