### ISSUE TITLE
Seed Graphics

### ISSUE THREAD

**Issue by DizzyIoeuy** [notfood/RimWorld-SeedsPlease#37]
Here are the graphics. A few of them may have incorrect names, so double check. The ones outside of folder structure may be in folders already and are identical, except the ASPEN ones- those have no folder yet.
[seed graphics.zip](https://github.com/notfood/RimWorld-SeedsPlease/files/6872003/seed.graphics.zip)

**Comment by notfood** [comment]
Do you have the autogenerated log? This looks the same as the one that is already included except for a few new textures. But I don't have the names, I can't work with textures alone.

**Comment by notfood** [comment]
I went one by one to check who was missing. I have `BogpineSeed.png` as extra. Where does it point?

**Comment by Frydendahl** [comment]
I'm guessing it's for the spruce pine in the cold bog mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2182111148

**Comment by DizzyIoeuy** [comment]
If the graphics match the tree, that would indicate it's the right seeds. The seed packets in folders are set to simply be dropped into the texture setup seeds please has. Anyone outside of the a folder are, as you noticed, perhaps identical but I wasn't entirely sure and wanted to make sure you had everything.

Correct, Aspen has no folder because seeds please released without that mod of his being included. They'll need to go in, but idk what folder name you all will give it , so I just gave you graphic seed packets.  Your naming convention for the folder wasn't consistent.

**Comment by DizzyIoeuy** [comment]
Wondering if you'll bonsai tree seed packet- I don't know how those work in the game, if they spontaneously generate or are planted- haven't made one yet.

**Comment by DizzyIoeuy** [comment]
> 
> 
> I'm guessing it's for the spruce pine in the cold bog mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2182111148
> 
> The graphics match that tree at least.

Yep the internal names and the display names don't match... So I go with the internal coded one.

**Comment by DizzyIoeuy** [comment]
Also for myself I'll be redoing all the seed packets in the VCE. They are pretty awful and look mostly like jam spread on toasts. I think they should feature the plant and not the product in a box for easier visual representation.  If you want those when I'm done and will use them, you can have copies.

Finally, if there's a higher rez version of the seed back beyond the 64x64 one I have my hands on, point me to it and I'll use it.

**Comment by notfood** [comment]
From the zip I used:
- nutrifungus
- fibercorn
- timbershroom
- tinctoria

Where do I put?
- AngelWingsCactusSeed
- KarimSeed
- OrangePineSeed
- RG-VIC_Plant_ArcticTreePine
- RedAspen
- SprucePineSeed
- YellowAspen
- palm tree seeds

The rest of the images already existed and were equal.

**Comment by DizzyIoeuy** [comment]
The aspen trees are for this mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2545774148&searchtext=aspen

OrangePineSeed is for:
https://steamcommunity.com/sharedfiles/filedetails/?id=2106597000&searchtext=regrowth

VIC_Plant_ArcticTreePine is for
https://steamcommunity.com/sharedfiles/filedetails/?id=2107412614&searchtext=regrowth

angelwing is likely a duplicate I already had it inthe folder for you for desert.

Karim and SprucePineSeed :
https://steamcommunity.com/sharedfiles/filedetails/?id=2182111148&searchtext=regrowth

You will have to name them all correctly, those were quick commissions for the guy doing the mega patch and he renamed them all to work right. I don't know why he didn't just forward them. Maybe some are already in the right places?

**Comment by DizzyIoeuy** [comment]
Go to those pages scroll down and see for yourself, they are all listed there.

**Comment by DizzyIoeuy** [comment]
Oh the Palm Tree:
 was to replace the one already in the desert folder as he didn't like the single tree- whichever looks nicer is fine with me
