### ISSUE TITLE
Anima Gear Patch

### ISSUE THREAD

**Issue by Americangrit1** [notfood/RimWorld-SeedsPlease#39]
I tried to patch Anima Gear and I got the defs loaded in and added the seed graphic but I can't seem to get the RecipeDef ParentName="ExtractSeed" to work for it.

[xrusha.AnimaGear.zip](https://github.com/notfood/RimWorld-SeedsPlease/files/6883872/xrusha.AnimaGear.zip)

**Comment by notfood** [comment]
What's the id of the mod?

**Comment by Americangrit1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2215217049

**Comment by Americangrit1** [comment]
When you say ID do you mean packageID? If so, its: xrushha.AnimaGear

**Comment by notfood** [comment]
Works fine
![image](https://user-images.githubusercontent.com/5370107/127437080-8ed98a6e-2766-4dca-9ad1-fc914b052732.png)

**Comment by notfood** [comment]
Closed by 3160d14de7bedbdc3de736c9e8b28aca2645389a
