### ISSUE TITLE
You lie about your licensing and are trying to claim this mod inappropriately

### ISSUE THREAD

**Issue by DizzyIoeuy** [notfood/RimWorld-SeedsPlease#42]
Your OWN licensing states:
https://creativecommons.org/licenses/by-nc-sa/4.0/

Yet, you get all pissy about forks.

Hm... you're a petty, tyrannical little girl. Obey your own licensing or change it- OOPS looks like you CAN'T change it as you assumed the license from the PREVIOUS versions of this mod which you did NOT originate!

**Comment by DizzyIoeuy** [comment]
And you stole my art, and massive amounts of XML coding others did over about a year, thief.

**Comment by notfood** [comment]
Feel free to take and compile it, and fix the errors too. Feel free to create a PR to remove your art.

Your attitude pissed me off.
